### ISSUE TITLE
Uwp hermes mqtt client error

### ISSUE THREAD

**Issue by jhalbrecht** [jhalbrecht/SampleXamFormsWithNetStandard#3]
The object of this repository is to get [Xamarin hermes mqtt](https://github.com/xamarin/mqtt) working in Android and Uwp in a .net Standard Xamarin.Forms library. Hopefully ios as well.

So far it works in the Android application. I get the following error in the Uwp app.

```
System.AggregateException: One or more errors occurred. (An error occurred while trying to connect the client XamarinClient) ---> System.Net.Mqtt.MqttClientException: An error occurred while trying to connect the client XamarinClient ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Mqtt.Sdk.TaskRunner'.
   at System.Net.Mqtt.Sdk.TaskRunner.Run(Func`1 func)
   at System.Net.Mqtt.Sdk.MqttClientImpl.<SendPacketAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__28.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__28.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at MqttTest.Data.Services.MqttDataServices.Connect()
---> (Inner Exception #0) System.Net.Mqtt.MqttClientException: An error occurred while trying to connect the client XamarinClient ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Mqtt.Sdk.TaskRunner'.
   at System.Net.Mqtt.Sdk.TaskRunner.Run(Func`1 func)
   at System.Net.Mqtt.Sdk.MqttClientImpl.<SendPacketAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__28.MoveNext()
   --- End of inner exception stack trace ---
   at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__28.MoveNext()<---

```

**Comment by jhalbrecht** [comment]
I get the above error when debugging the UWP app after building in Visual Studio. I tried using msbuild from a VS command prompt then debugged. It worked!

I suppose a new issues would be in order to work on building from Visual Studio.
